--- 
title: "胃癌基因组差异甲基化区域(DMR)"
author: "武汉艾米森生命科技有限公司"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book

---


  

```{r eval=FALSE,echo=FALSE}
options(knitr.table.format = "html") 
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")

```


# 样本信息
```{r sampleInf,echo=FALSE}
dataDir <- 'F:/projects/UCEC/output/Report/'
    library(rmarkdown)
    library(knitr)
    library(kableExtra)
    sampleInf <- read.csv(paste0(dataDir,"SampleInf.csv"),stringsAsFactors = F)
    kable(sampleInf)

```

# 差异甲基化区(DMR)

```{r DMRInf,echo=FALSE,results="asis",include=T,knitr.table.format = 'html'}
      library(tidyr)
      library(kableExtra)
      #library(xtable)
    
    files <- list.files(path=dataDir)
    dmrFiles <- files[grepl('DMR_',files)]
    indx <- as.integer(sapply(dmrFiles,function(v){strsplit(v,"_")[[1]][2]}))
    dmrFiles <- dmrFiles[sort(indx)]
    sites <- as.character(sapply(dmrFiles,function(v){a <- strsplit(v,"_")[[1]][3];b=strsplit(a,"\\.")[[1]][1];b}))
  

    for(i in 1:length(sites)){
       cat('##  ',sites[i])
       obj <- read.csv(paste0(dataDir,dmrFiles[i]),header = T,stringsAsFactors = F) 
       cat("\n")
       tb <- obj[1:1000,] %>%
       kable(format = "html",row.names = FALSE) %>%
                column_spec(1, width = "10em", background = "yellow")
      
       
      print(tb)
   
       cat("\n")
    }
```
