--- 
title: "结直肠癌差异甲基化区域\\ "
author: 
- '\ ' 
- "艾米森生命科技有限公司"
- '生物信息部' 
- '\ '  
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# 问题描述

SDC2 三个DMR的序列和位置已经发给您，烦请补充以下结果：
     首先，将390多例癌症样本按照部位进行分类（如直肠、乙状结肠、升结肠等等）
     对于每个部位的癌症，做6条ROC曲线，分别是单个DMR的ROC和两个DMR
     组合的ROC，各三个。
     谢谢！


```{r eval=FALSE,echo=F}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```

Remember each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`.

To compile this example to PDF, you need XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.name/tinytex/>.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
```{r eval=TRUE,include=T,echo=F,results='asis'}
for(i in 1:10){
 cat(sprintf('##  question %d \n\s', i))
}


```